[CPV] cg bug fix: the lambda matrix calculation was incorrect beause of a refactoring of few commits ago
the problem was more evident in the ultrasoft case

[CPV] fix gpu compilation and run

all tests for cp are passing on CPU

output of test suite for cp on GPU:

env QE_USE_MPI=1 /m100/home/userexternal/rbertoss/q-e_rikigigi/test-suite/..//test-suite/testcode/bin/testcode.py --verbose --category=cp_all
Using executable: /m100/home/userexternal/rbertoss/q-e_rikigigi/test-suite/..//test-suite/run-cp.sh.
Test id: 141121-2.
Benchmark: git.

cp_h2o - h2o-mt-blyp-1.in: Passed.

cp_h2o - h2o-mt-blyp-2.in: Passed.

cp_h2o - h2o-mt-blyp-3.in: Passed.

cp_h2o - h2o-mt-blyp-4.in: Passed.

cp_h2o - h2o-mt-blyp-5.in: Passed.

cp_h2o - h2o-mt-blyp-6.in: Passed.

cp_h2o - h2o-mt-blyp-cg.in: **FAILED**.
s1
    ERROR: absolute error 8.45e-04 greater than 5.00e-04. (Test: 0.62446197.  Benchmark: 0.6253067.)
    ERROR: relative error 1.35e-03 greater than 1.00e-04. (Test: 0.62446197.  Benchmark: 0.6253067.)

cp_h2o_exx - h2o-mt-b3lyp-1.in: Passed.

cp_h2o_scan_libxc - nspin1.in: SKIPPED.

cp_h2o_scan_libxc - nspin2.in: SKIPPED.

cp_h2o_wf - h2o-nspin1.in: Passed.

cp_h2o_wf - h2o-nspin2.in: Passed.

cp_o2 - o2-us-para-pbe-1.in: Passed.

cp_o2 - o2-us-para-pbe-2.in: Passed.

cp_o2 - o2-us-para-pbe-3.in: Passed.

cp_o2 - o2-us-para-pbe-4.in: Passed.

cp_o2 - o2-us-para-pbe-5.in: Passed.

cp_o2 - o2-us-para-pbe-6.in: Passed.

cp_si - si-vbc-lda-1.in: Passed.

cp_si - si-vbc-lda-2.in: Passed.

cp_si - si-vbc-lda-3.in: Passed.

cp_sio2 - sio2-us-lda-1.in: **FAILED**.
e1
    ERROR: absolute error 6.30e-05 greater than 1.00e-05. (Test: -202.503718.  Benchmark: -202.503655.)

cp_sio2 - sio2-us-lda-2.in: Passed.

cp_sio2 - sio2-us-lda-3.in: **FAILED**.
s1
    ERROR: absolute error 4.56e+00 greater than 5.00e-04. (Test: -0.6937499.  Benchmark: -5.25597336.)
    ERROR: relative error 8.68e-01 greater than 1.00e-04. (Test: -0.6937499.  Benchmark: -5.25597336.)
e1
    ERROR: absolute error 3.17e-03 greater than 1.00e-05. (Test: -212.029823.  Benchmark: -212.032996.)
    ERROR: relative error 1.50e-05 greater than 1.00e-05. (Test: -212.029823.  Benchmark: -212.032996.)
t1
    ERROR: absolute error 3.04e+01 greater than 6.00e-03. (Test: 31.38795.  Benchmark: 61.8084.)
    ERROR: relative error 4.92e-01 greater than 1.00e-03. (Test: 31.38795.  Benchmark: 61.8084.)
v1u
    ERROR: absolute error 8.60e-01 greater than 1.00e-02. (Test: -221.64.  Benchmark: -220.78.)

cp_sio2 - sio2-us-lda-4.in: **FAILED**.
s1
    ERROR: absolute error 6.52e-01 greater than 5.00e-04. (Test: 3.32396042.  Benchmark: 3.97590607.)
    ERROR: relative error 1.64e-01 greater than 1.00e-04. (Test: 3.32396042.  Benchmark: 3.97590607.)
e1
    ERROR: absolute error 2.12e-02 greater than 1.00e-05. (Test: -211.992762.  Benchmark: -212.013964.)
    ERROR: relative error 1.00e-04 greater than 1.00e-05. (Test: -211.992762.  Benchmark: -212.013964.)
t1
    ERROR: absolute error 1.08e+01 greater than 6.00e-03. (Test: 152.1087.  Benchmark: 162.94203.)
    ERROR: relative error 6.65e-02 greater than 1.00e-03. (Test: 152.1087.  Benchmark: 162.94203.)
v1u
    ERROR: absolute error 3.69e+00 greater than 1.00e-02. (Test: -220.63.  Benchmark: -216.94.)
    ERROR: relative error 1.70e-02 greater than 1.00e-02. (Test: -220.63.  Benchmark: -216.94.)

cp_sio2 - sio2-us-lda-cg.in: **FAILED**.
Different sets of data extracted from benchmark and test.
    Data only in benchmark: t1, e1, v1u.

All done. ERROR: only 19 out of 24 tests passed (2 skipped).
Failed tests in:
	/m100/home/userexternal/rbertoss/q-e_rikigigi/test-suite/cp_h2o/
	/m100/home/userexternal/rbertoss/q-e_rikigigi/test-suite/cp_sio2/
Skipped tests in:
	/m100/home/userexternal/rbertoss/q-e_rikigigi/test-suite/cp_h2o_scan_libxc/
make: *** [Makefile:56: run-tests-cp-parallel] Error 1

[CPV] fixed issue with lambda matrix, introduced bug in GPU version, cg restart routine

bug moved to a different routine (?!)

fixed bug introduced with previous commit